PR for #67:  Julia extension
gentzkow/template pull request #68
Opened 2022-10-11 20:37 UTC by jc-cisneros

This pull request closes https://github.com/gslab-econ/gslab_make/issues/54 and #67. This `template` branch is currently pulling the 54-create-run_julia branch of the `gslab_make` submodule, so PR for 54 should be closed first.

The proposed steps to test the new julia wrapper are the following:
- Clone `template` and switch to `67-julia-extension` branch
- Create the `template_julia` conda environment (i.e., run `conda env create -f setup/conda_env.yaml` from root)
- Update the submodule and check it is pulling the `54-create-run_julia` branch of gslab_make:
```
git submodule init
git submodule update
git submodule status
```
The submodule should be pointing to ` 493a368af77af97ea7403d8f3e176f3d1e0af7a0 lib/gslab_make (heads/54-create-run_julia)`

- Activate the `template_julia` environment. Run `check_setup.py` from the `setup` module.
- Run `run_all.py` from root. A new Julia script will be called on the analysis module. The file `julia_scatter.png` should be created and saved in `analysis/output`  

Once the tests are successful, we can proceed to merge  the `54-create-run_julia` branch of gslab_make to `master` (through PR for 54), point the submodule to `master` and run the entire repo again.

2022-10-11 21:43 UTC, snairdesai commented
@jc-cisneros I think we will need to update the `submodule` to point to the development branch commit you reference; it is currently still pointing to the latest commit in `master`. I'll re-review following this change.

2022-10-12 17:01 UTC, jc-cisneros commented
@snairdesai I updated the instructions to fetch the correct submodule. The additional error you were getting regarding the packages (e.g. `run_julia() throwing the error that it did not find any of the install packages`) has been fixed on my end. In particular we want to run `julia  --project=.. <filepath>` instead of `julia  <filepath>`. By doing that, we use the Julia environment that was instantiated in root.

2022-10-12 18:31 UTC, snairdesai commented
Thanks @jc-cisneros! I'll proceed with the review then.

2022-10-13 01:34 UTC, jc-cisneros commented
Thanks @snairdesai ! I rebuilt the `Manifest.toml` and `Project.toml` files. I uninstalled my local Julia and cleared my `.julia` cache. The run was successful in my end. Let me know if it works for you @snairdesai.

![Screen Shot 2022-10-12 at 6 30 42 PM](https://user-images.githubusercontent.com/108437517/195478413-cf0ae1c8-c47b-4d7f-a690-1896df5daf17.png)

2022-10-13 04:47 UTC, snairdesai commented
@jc-cisneros still no luck - here's the new error messages from the `PyCall` build:

<img width="1130" alt="Screen Shot 2022-10-12 at 9 46 53 PM" src="https://user-images.githubusercontent.com/63830369/195503937-2a3a2462-4161-4338-9c06-86f1ed67642b.png">

2022-10-13 20:42 UTC, jc-cisneros commented
@snairdesai I changed the process to build the Julia environment using a script instead of the .toml files. The `Manifest.toml` and `Project.toml` files will now be created in the `/conda/base/envs/template_julia/share/julia/environments/template_julia`directory (i.e., the Julia installed in the conda environment is managing a `template_julia` Julia environment with Pkg). Let me know if everything works on your end.

2022-10-13 21:24 UTC, snairdesai commented
@jc-cisneros No luck - errors seem a bit more severe. I've attached some screenshots below:

---

<img width="1434" alt="Screen Shot 2022-10-13 at 2 22 09 PM" src="https://user-images.githubusercontent.com/63830369/195713227-9ab092b2-9723-4957-81e9-76920c4295ff.png">

---

<img width="1439" alt="Screen Shot 2022-10-13 at 2 22 30 PM" src="https://user-images.githubusercontent.com/63830369/195713281-0121c284-0998-4b29-81e9-1cf5c05c293e.png">

---

<img width="1023" alt="Screen Shot 2022-10-13 at 2 22 55 PM" src="https://user-images.githubusercontent.com/63830369/195713360-670c5ed2-3e54-4c34-9f21-901fedf8cecd.png">

---

<img width="1439" alt="Screen Shot 2022-10-13 at 2 23 20 PM" src="https://user-images.githubusercontent.com/63830369/195713433-f1ecbc7e-0e98-4767-b5a4-4a180eb58b9e.png">

---

<img width="1438" alt="Screen Shot 2022-10-13 at 2 23 51 PM" src="https://user-images.githubusercontent.com/63830369/195713529-87d0deab-f8d8-45f7-a826-7af06c91cebd.png">

2022-10-15 01:02 UTC, jc-cisneros commented
@snairdesai I have not encountered this error on my end, but my current best guess is that it might be related to the Python distribution the Julia environment is pointing to. The error message states that it is indeed using the Python distribution in the Conda package, but it might be using a Python distribution you have on your `miniconda/base/bin` instead of the one in your `template julia` environment. Let me test a possible solution on my end, and I will let you know when you can give it another try. Thank you!

2022-10-18 01:14 UTC, jc-cisneros commented
@snairdesai building the Conda environment + Julia environment setup has been tricky (trickier than writing the wrapper). I have completed a full run on a Docker Debian container ([8b1c26b](https://github.com/gentzkow/template/pull/68/commits/8b1c26b6f6a3e1b0c61972facb033fcd8c2600a0)) and on my local Mac OS afterwards ([4863c67](https://github.com/gentzkow/template/pull/68/commits/4863c67b051bd00dc73c8e9f70f86d0a95ad4e0b)). The Conda.jl package should be capable of dealing with the Python path issue. Let me know if it works on your end.

2022-10-18 18:23 UTC, snairdesai commented
@jc-cisneros Flagging I have the same errors as in the [comment above](https://github.com/gentzkow/template/pull/68#issuecomment-1278194409).

<img width="1344" alt="Screen Shot 2022-10-18 at 11 22 11 AM" src="https://user-images.githubusercontent.com/63830369/196513065-085a3128-4a4d-4f94-98fe-3bcf6e86edbd.png">

---

<img width="885" alt="Screen Shot 2022-10-18 at 11 23 20 AM" src="https://user-images.githubusercontent.com/63830369/196513155-a58457e7-9909-4a82-97e9-2f5d04ea539b.png">

2022-10-20 18:09 UTC, jc-cisneros commented
Thanks @snairdesai! Let me explain the latest changes:
- All of the errors above are caused by the `PyCall.jl` package. By default, this package uses the Python version in the Conda directory. This might lead to issues when there are several Python versions living in the Conda directory (i.e. there are several environments). We can fix this in an interactive Julia session by changing the path of the Python Environment variable. Nevertheless, to make this change global we might have to touch a user configuration file after creating the Conda environment (see https://docs.julialang.org/en/v1/manual/environment-variables/). I think being able to call Python functions within Julia is not a feature we really need (we could simply run Python scripts within the same project), so this effort is not worth pursuing and it is out of the scope of this PR. 
- The new test script does not use the `matplotlib` backend for the plot. @snairdesai let me know if the version conflicts are gone and if the `run_julia` wrapper works.

2022-10-20 21:57 UTC, snairdesai commented
@jc-cisneros We're very close here - the plots are compiling now. Small issue, I had another terminal window open on my local computer when the Julia script ran, which I had to manually exit out of for the code to finish compiling. Ideally we would want this to automatically exit for the user. A screenshot of the outputs are below:

---

<img width="565" alt="Screen Shot 2022-10-20 at 2 55 31 PM" src="https://user-images.githubusercontent.com/63830369/197066553-69448547-4f20-4eb5-a464-b7a3d779b726.png">

<img width="639" alt="Screen Shot 2022-10-20 at 2 56 48 PM" src="https://user-images.githubusercontent.com/63830369/197066575-5d20491f-365e-45a9-a416-9b9b9165d73d.png">

2022-10-21 18:15 UTC, snairdesai commented
@jc-cisneros Post your latest commit [`a45a0a2`](https://github.com/gentzkow/template/pull/68/commits/a45a0a23bbfd0cd06e0ef44759a2a4c8644db3a7) - this compiles successfully! I'll proceed to a code review now.

2022-10-21 18:29 UTC, snairdesai commented on julia_conda_env.jl
> +Pkg.add(["DataFrames", "CSV", "StatsPlots", "Plots", "GR"])
@jc-cisneros For a future PR (perhaps not this one), we probably want to:

1. specify versions of these packages explicitly, to maintain the transition to this format across R and Python
2. in our `check_setup` script, notify the user if they have not properly installed the correct Julia packages.

Just tagging this here.

2022-10-21 18:29 UTC, snairdesai commented on analysis/code/plot.jl
> +run(`killall -9 gksqt`)
@jc-cisneros 

Interesting way to kill the terminal plot environment, agree it's the best we have for now.

2022-10-21 18:30 UTC, snairdesai commented on setup/conda_env.yaml
>    #     - EXAMPLE_PACKAGE
@jc-cisneros 

We'll want to track developments made by the `conda-forge` team such that when they have implemented the proper fixes, we migrate the calls to Julia and package installer directly to this `conda_env.yaml` file, rather than our separate `julia_conda_env.jl` script (much like we do for `pip` in R.

2022-10-21 18:32 UTC, snairdesai requested changes
Small comment on the `conda_env.yaml` package versions, but otherwise this looks good! Hopefully the `conda-forge` developments coming down the pipeline will make this process easier.

2022-10-21 18:32 UTC, snairdesai commented on setup/conda_env.yaml
>    - pyyaml # import python packages by naming them as dependencies and potentially specifying version numbers
@jc-cisneros We want to add version numbers commented out here to match `master`, no?

2022-10-21 19:51 UTC, jc-cisneros commented on setup/conda_env.yaml
>    - pyyaml # import python packages by naming them as dependencies and potentially specifying version numbers
Thank you @snairdesai! I agree.

2022-10-21 20:10 UTC, jc-cisneros commented
@snairdesai thanks for the careful review! In the latest commit [8f0cec7](https://github.com/gentzkow/template/pull/68/commits/8f0cec7027c3a5d90aaa096c15e7e1009084e71e), I added the versions of all packages used (as in master). I also commented out all the Julia-related lines, so that the default behavior in master is not installing Julia and producing the test plot. Throughout all these tests, the `run_julia` wrapper has been working as expected. I will stress in the final summary that until the julia-feedstock is further developed on conda-forge (see https://github.com/gentzkow/template/issues/67#issuecomment-1273944247), we will need this `julia_conda_env.jl` workaround (which as shown in this PR, can create conflicts if Python is called from Julia). 

If everything looks good, I will proceed to merge the development branches of this PR and [the PR on gslab_make](https://github.com/gslab-econ/gslab_make/pull/55) to their respective `master` branches. The final step then would be to add summaries that close #67 and [#54 on gslab_make](https://github.com/gslab-econ/gslab_make/issues/54).

2022-10-22 00:49 UTC, Houdanait commented
Hey @jc-cisneros @snairdesai !
Thanks so much for all the brilliant work here ! 
Please ping me once you're done merging this to the template as we will need this extension in another repo !

2022-10-22 00:55 UTC, snairdesai approved these changes
Thanks @jc-cisneros! The revisions look good to me - I'm approving this PR, and simultaneously the one for [#54](https://github.com/gslab-econ/gslab_make/issues/54) on `gslab_make`.

2022-10-22 01:33 UTC, jc-cisneros commented
Thanks again for the review, @snairdesai! I will close the issues with a summary and merge this branch to master.

2022-10-22 01:33 UTC, merged